In [3]:
import pandas as pd

In [4]:
pd.DataFrame({'Yes': [50, 21], 'No': [131, 2]})

   Yes   No
0   50  131
1   21    2

In [5]:
pd.DataFrame({'Bob': ['I liked it', 'It was awful'], 'Sue': ['Pretty good', 'Bland']})

            Bob          Sue
0    I liked it  Pretty good
1  It was awful        Bland

In [6]:
pd.DataFrame({'Bob': ['I liked it', 'It was awful'], 'Sue': ['Pretty good', 'Bland']}, index=['Product A', 'Product B'])

                    Bob          Sue
Product A    I liked it  Pretty good
Product B  It was awful        Bland

In [7]:
pd.Series([1, 2, 3, 4, 5])

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [8]:
pd.Series([30, 35, 40], index=['2015 Sales', '2016 Sales', '2017 Sales'], name='Product A')

2015 Sales    30
2016 Sales    35
2017 Sales    40
Name: Product A, dtype: int64

In [9]:
reviews = pd.DataFrame({'Bob': ['I liked it', 'It was awful'], 'Sue': ['Pretty good', 'Bland']}, index=['Product A', 'Product B'])

In [10]:
reviews

                    Bob          Sue
Product A    I liked it  Pretty good
Product B  It was awful        Bland

In [11]:
reviews.Bob

Product A      I liked it
Product B    It was awful
Name: Bob, dtype: object

In [12]:
reviews['Bob']

Product A      I liked it
Product B    It was awful
Name: Bob, dtype: object

In [13]:
reviews['Bob'][0]

'I liked it'

In [14]:
reviews.iloc[0]

Bob     I liked it
Sue    Pretty good
Name: Product A, dtype: object

In [15]:
reviews.iloc[:2, 0]

Product A      I liked it
Product B    It was awful
Name: Bob, dtype: object

In [16]:
reviews.loc['Product A', 'Bob']

'I liked it'

In [17]:
reviews.Bob == 'I liked it'

Product A     True
Product B    False
Name: Bob, dtype: bool

In [18]:
reviews.loc[reviews.Bob == 'I liked it']

                  Bob          Sue
Product A  I liked it  Pretty good

In [19]:
reviews['Mike'] = 'Good'

In [20]:
reviews

                    Bob          Sue  Mike
Product A    I liked it  Pretty good  Good
Product B  It was awful        Bland  Good

# Lecture 3. Summary functions and Maps

In [23]:
wines_filepath = 'winemag-data-130k-v2.csv'
reviews = pd.read_csv(wines_filepath, index_col=0)
reviews

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks
...,...,...,...,...,...,...,...,...,...,...,...,...,...
129966,Germany,Notes of honeysuckle and cantaloupe sweeten th...,Brauneberger Juffer-Sonnenuhr Spätlese,90,28.0,Mosel,NaN,NaN,Anna Lee C. Iijima,NaN,Dr. H. Thanisch (Erben Müller-Burggraef) 2013 ...,Riesling,Dr. H. Thanisch (Erben Müller-Burggraef)
129967,US,Citation is given as much as a decade of bottl...,NaN,90,75.0,Oregon,Oregon,Oregon Other,Paul Gregutt,@paulgwine,Citation 2004 Pinot Noir (Oregon),Pinot Noir,Citation
129968,France,Well-drained gravel soil gives this wine its c...,Kritt,90,30.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Gresser 2013 Kritt Gewurztraminer (Als...,Gewürztraminer,Domaine Gresser
129969,France,"A dry style of Pinot Gris, this is crisp with ...",NaN,90,32.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Marcel Deiss 2012 Pinot Gris (Alsace),Pinot Gris,Domaine Marcel Deiss
129970,France,"Big, rich and off-dry, this is powered by inte...",Lieu-dit Harth Cuvée Caroline,90,21.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Schoffit 2012 Lieu-dit Harth Cuvée Car...,Gewürztraminer,Domaine Schoffit

In [24]:
reviews.points.describe()

count    129971.000000
mean         88.447138
std           3.039730
min          80.000000
25%          86.000000
50%          88.000000
75%          91.000000
max         100.000000
Name: points, dtype: float64

In [25]:
reviews.taster_name.describe()

count         103727
unique            19
top       Roger Voss
freq           25514
Name: taster_name, dtype: object

In [26]:
reviews.points.mean()

88.44713820775404

In [27]:
reviews.taster_name.unique()

array(['Kerin O’Keefe', 'Roger Voss', 'Paul Gregutt',
       'Alexander Peartree', 'Michael Schachner', 'Anna Lee C. Iijima',
       'Virginie Boone', 'Matt Kettmann', nan, 'Sean P. Sullivan',
       'Jim Gordon', 'Joe Czerwinski', 'Anne Krebiehl\xa0MW',
       'Lauren Buzzeo', 'Mike DeSimone', 'Jeff Jenssen',
       'Susan Kostrzewa', 'Carrie Dykes', 'Fiona Adams',
       'Christina Pickard'], dtype=object)

In [28]:
reviews.taster_name.value_counts()

Roger Voss            25514
Michael Schachner     15134
Kerin O’Keefe         10776
Virginie Boone         9537
Paul Gregutt           9532
Matt Kettmann          6332
Joe Czerwinski         5147
Sean P. Sullivan       4966
Anna Lee C. Iijima     4415
Jim Gordon             4177
Anne Krebiehl MW       3685
Lauren Buzzeo          1835
Susan Kostrzewa        1085
Mike DeSimone           514
Jeff Jenssen            491
Alexander Peartree      415
Carrie Dykes            139
Fiona Adams              27
Christina Pickard         6
Name: taster_name, dtype: int64

In [32]:
reviews_points_mean = reviews.points.mean()
reviews.points.map(lambda p: p - reviews_points_mean)

0        -1.447138
1        -1.447138
2        -1.447138
3        -1.447138
4        -1.447138
            ...
129966    1.552862
129967    1.552862
129968    1.552862
129969    1.552862
129970    1.552862
Name: points, Length: 129971, dtype: float64

In [37]:
def remean_points(row):
    row.points = row.points - reviews_points_mean
    return row
reviews.apply(remean_points, axis='columns')

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,-1.447138,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,-1.447138,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,-1.447138,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,-1.447138,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,-1.447138,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks
...,...,...,...,...,...,...,...,...,...,...,...,...,...
129966,Germany,Notes of honeysuckle and cantaloupe sweeten th...,Brauneberger Juffer-Sonnenuhr Spätlese,1.552862,28.0,Mosel,NaN,NaN,Anna Lee C. Iijima,NaN,Dr. H. Thanisch (Erben Müller-Burggraef) 2013 ...,Riesling,Dr. H. Thanisch (Erben Müller-Burggraef)
129967,US,Citation is given as much as a decade of bottl...,NaN,1.552862,75.0,Oregon,Oregon,Oregon Other,Paul Gregutt,@paulgwine,Citation 2004 Pinot Noir (Oregon),Pinot Noir,Citation
129968,France,Well-drained gravel soil gives this wine its c...,Kritt,1.552862,30.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Gresser 2013 Kritt Gewurztraminer (Als...,Gewürztraminer,Domaine Gresser
129969,France,"A dry style of Pinot Gris, this is crisp with ...",NaN,1.552862,32.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Marcel Deiss 2012 Pinot Gris (Alsace),Pinot Gris,Domaine Marcel Deiss
129970,France,"Big, rich and off-dry, this is powered by inte...",Lieu-dit Harth Cuvée Caroline,1.552862,21.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Schoffit 2012 Lieu-dit Harth Cuvée Car...,Gewürztraminer,Domaine Schoffit

In [38]:
review_points_mean = reviews.points.mean()
reviews.points - review_points_mean

0        -1.447138
1        -1.447138
2        -1.447138
3        -1.447138
4        -1.447138
            ...
129966    1.552862
129967    1.552862
129968    1.552862
129969    1.552862
129970    1.552862
Name: points, Length: 129971, dtype: float64

In [39]:
reviews.country + "-" + reviews.region_1

0                     Italy-Etna
1                            NaN
2           US-Willamette Valley
3         US-Lake Michigan Shore
4           US-Willamette Valley
                   ...
129966                       NaN
129967                 US-Oregon
129968             France-Alsace
129969             France-Alsace
129970             France-Alsace
Length: 129971, dtype: object

Map and apply are more advanced
while built-in are faster

# Lecture 4. Grouping and sorting

In [40]:
reviews.groupby('points').points.count()

points
80       397
81       692
82      1836
83      3025
84      6480
85      9530
86     12600
87     16933
88     17207
89     12226
90     15410
91     11359
92      9613
93      6489
94      3758
95      1535
96       523
97       229
98        77
99        33
100       19
Name: points, dtype: int64

In [43]:
reviews.groupby('points').price.min()

points
80      5.0
81      5.0
82      4.0
83      4.0
84      4.0
85      4.0
86      4.0
87      5.0
88      6.0
89      7.0
90      8.0
91      7.0
92     11.0
93     12.0
94     13.0
95     20.0
96     20.0
97     35.0
98     50.0
99     44.0
100    80.0
Name: price, dtype: float64

In [44]:
reviews.groupby('winery').apply(lambda df: df.title.iloc[0])

winery
1+1=3                                     1+1=3 NV Rosé Sparkling (Cava)
10 Knots                            10 Knots 2010 Viognier (Paso Robles)
100 Percent Wine              100 Percent Wine 2015 Moscato (California)
1000 Stories           1000 Stories 2013 Bourbon Barrel Aged Zinfande...
1070 Green                  1070 Green 2011 Sauvignon Blanc (Rutherford)
                                             ...
Órale                       Órale 2011 Cabronita Red (Santa Ynez Valley)
Öko                    Öko 2013 Made With Organically Grown Grapes Ma...
Ökonomierat Rebholz    Ökonomierat Rebholz 2007 Von Rotliegenden Spät...
àMaurice               àMaurice 2013 Fred Estate Syrah (Walla Walla V...
Štoka                                    Štoka 2009 Izbrani Teran (Kras)
Length: 16757, dtype: object

In [46]:
reviews.groupby(['country', 'province']).apply(lambda df: df.loc[df.points.idxmax()])

                              country  \
country   province
Argentina Mendoza Province  Argentina
          Other             Argentina
Armenia   Armenia             Armenia
Australia Australia Other   Australia
          New South Wales   Australia
...                               ...
Uruguay   Juanico             Uruguay
          Montevideo          Uruguay
          Progreso            Uruguay
          San Jose            Uruguay
          Uruguay             Uruguay

                                                                  description  \
country   province
Argentina Mendoza Province  If the color doesn't tell the full story, the ...
          Other             Take note, this could be the best wine Colomé ...
Armenia   Armenia           Deep salmon in color, this wine offers a bouqu...
Australia Australia Other   Writes the book on how to make a wine filled w...
          New South Wales   De Bortoli's Noble One is as good as ever in 2...
...                                                                       ...
Uruguay   Juanico           This mature Bordeaux-style blend is earthy on ...
          Montevideo        A rich, heady bouquet offers aromas of blackbe...
          Progreso          Rusty in color but deep and complex in nature,...
          San Jose          Baked, sweet, heavy aromas turn earthy with ti...
          Uruguay           Cherry and berry aromas are ripe, healthy and ...

                                                        designation  points  \
country   province
Argentina Mendoza Province                         Nicasia Vineyard      97
          Other                                             Reserva      95
Armenia   Armenia                                    Estate Bottled      88
Australia Australia Other                             Sarah's Blend      93
          New South Wales                        Noble One Bortytis      94
...                                                             ...     ...
Uruguay   Juanico                  Preludio Barrel Select Lote N 77      90
          Montevideo        Monte Vide Eu Tannat-Merlot-Tempranillo      91
          Progreso                   Etxe Oneko Fortified Sweet Red      90
          San Jose                         El Preciado Gran Reserva      87
          Uruguay                         Blend 002 Limited Edition      91

                            price          province                 region_1  \
country   province
Argentina Mendoza Province  120.0  Mendoza Province                  Mendoza
          Other              90.0             Other                    Salta
Armenia   Armenia            15.0           Armenia                      NaN
Australia Australia Other    15.0   Australia Other  South Eastern Australia
          New South Wales    32.0   New South Wales          New South Wales
...                           ...               ...                      ...
Uruguay   Juanico            45.0           Juanico                      NaN
          Montevideo         60.0        Montevideo                      NaN
          Progreso           46.0          Progreso                      NaN
          San Jose           50.0          San Jose                      NaN
          Uruguay            22.0           Uruguay                      NaN

                           region_2        taster_name taster_twitter_handle  \
country   province
Argentina Mendoza Province      NaN  Michael Schachner           @wineschach
          Other                 NaN  Michael Schachner           @wineschach
Armenia   Armenia               NaN      Mike DeSimone        @worldwineguys
Australia Australia Other       NaN                NaN                   NaN
          New South Wales       NaN     Joe Czerwinski                @JoeCz
...                             ...                ...                   ...
Uruguay   Juanico               NaN  Michael Schachner           @wineschach
          Montevideo            NaN  Michael Schachner           @wineschach
          Progreso              NaN  Michael Schachner           @wineschach
          San Jose              NaN  Michael Schachner           @wineschach
          Uruguay               NaN  Michael Schachner           @wineschach

                                                                        title  \
country   province
Argentina Mendoza Province  Bodega Catena Zapata 2006 Nicasia Vineyard Mal...
          Other                            Colomé 2010 Reserva Malbec (Salta)
Armenia   Armenia                 Van Ardi 2015 Estate Bottled Rosé (Armenia)
Australia Australia Other   Marquis Philips 2000 Sarah's Blend Red (South ...
          New South Wales   De Bortoli 2007 Noble One Bortytis Semillon (N...
...                                                                       ...
Uruguay   Juanico           Familia Deicas 2004 Preludio Barrel Select Lot...
          Montevideo        Bouza 2015 Monte Vide Eu Tannat-Merlot-Tempran...
          Progreso          Pisano 2007 Etxe Oneko Fortified Sweet Red Tan...
          San Jose          Castillo Viejo 2005 El Preciado Gran Reserva R...
          Uruguay           Narbona NV Blend 002 Limited Edition Tannat-Ca...

                                          variety                winery
country   province
Argentina Mendoza Province                 Malbec  Bodega Catena Zapata
          Other                            Malbec                Colomé
Armenia   Armenia                            Rosé              Van Ardi
Australia Australia Other               Red Blend       Marquis Philips
          New South Wales                Sémillon            De Bortoli
...                                           ...                   ...
Uruguay   Juanico                       Red Blend        Familia Deicas
          Montevideo                    Red Blend                 Bouza
          Progreso                         Tannat                Pisano
          San Jose                      Red Blend        Castillo Viejo
          Uruguay           Tannat-Cabernet Franc               Narbona

[425 rows x 13 columns]

In [47]:
reviews.groupby(['country']).price.agg([len, min, max])

                          len   min     max
country
Argentina                3800   4.0   230.0
Armenia                     2  14.0    15.0
Australia                2329   5.0   850.0
Austria                  3345   7.0  1100.0
Bosnia and Herzegovina      2  12.0    13.0
Brazil                     52  10.0    60.0
Bulgaria                  141   8.0   100.0
Canada                    257  12.0   120.0
Chile                    4472   5.0   400.0
China                       1  18.0    18.0
Croatia                    73  12.0    65.0
Cyprus                     11  11.0    21.0
Czech Republic             12  15.0    45.0
Egypt                       1   NaN     NaN
England                    74  25.0    95.0
France                  22093   5.0  3300.0
Georgia                    86   9.0    40.0
Germany                  2165   5.0   775.0
Greece                    466   8.0    79.0
Hungary                   146  10.0   764.0
India                       9  10.0    20.0
Israel                    505   8.0   150.0
Italy                   19540   5.0   900.0
Lebanon                    35  13.0    75.0
Luxembourg                  6  16.0    30.0
Macedonia                  12  15.0    20.0
Mexico                     70   8.0   108.0
Moldova                    59   8.0    42.0
Morocco                    28  14.0    40.0
New Zealand              1419   7.0   130.0
Peru                       16  10.0    68.0
Portugal                 5691   5.0  1000.0
Romania                   120   4.0   320.0
Serbia                     12  15.0    42.0
Slovakia                    1  16.0    16.0
Slovenia                   87   7.0    90.0
South Africa             1401   5.0   330.0
Spain                    6645   4.0   770.0
Switzerland                 7  21.0   160.0
Turkey                     90  14.0   120.0
US                      54504   4.0  2013.0
Ukraine                    14   6.0    13.0
Uruguay                   109  10.0   130.0

In [48]:
countries_reviewed = reviews.groupby(['country', 'province']).description.agg([len])
countries_reviewed

                             len
country   province
Argentina Mendoza Province  3264
          Other              536
Armenia   Armenia              2
Australia Australia Other    245
          New South Wales     85
...                          ...
Uruguay   Juanico             12
          Montevideo          11
          Progreso            11
          San Jose             3
          Uruguay             24

[425 rows x 1 columns]

In [49]:
mi = countries_reviewed.index
type(mi)

pandas.core.indexes.multi.MultiIndex

In [50]:
countries_reviewed.reset_index()

       country          province   len
0    Argentina  Mendoza Province  3264
1    Argentina             Other   536
2      Armenia           Armenia     2
3    Australia   Australia Other   245
4    Australia   New South Wales    85
..         ...               ...   ...
420    Uruguay           Juanico    12
421    Uruguay        Montevideo    11
422    Uruguay          Progreso    11
423    Uruguay          San Jose     3
424    Uruguay           Uruguay    24

[425 rows x 3 columns]

In [51]:
countries_reviewed = countries_reviewed.reset_index()
countries_reviewed.sort_values(by='len')

          country               province    len
179        Greece  Muscat of Kefallonian      1
192        Greece          Sterea Ellada      1
194        Greece                 Thraki      1
354  South Africa             Paardeberg      1
40         Brazil       Serra do Sudeste      1
..            ...                    ...    ...
409            US                 Oregon   5373
227         Italy                Tuscany   5897
118        France               Bordeaux   5941
415            US             Washington   8639
392            US             California  36247

[425 rows x 3 columns]

In [53]:
countries_reviewed.sort_values(by='len', ascending=False)

          country         province    len
392            US       California  36247
415            US       Washington   8639
118        France         Bordeaux   5941
227         Italy          Tuscany   5897
409            US           Oregon   5373
..            ...              ...    ...
101       Croatia              Krk      1
247   New Zealand        Gladstone      1
357  South Africa  Piekenierskloof      1
63          Chile          Coelemu      1
149        Greece           Beotia      1

[425 rows x 3 columns]

In [54]:
countries_reviewed.sort_index()

       country          province   len
0    Argentina  Mendoza Province  3264
1    Argentina             Other   536
2      Armenia           Armenia     2
3    Australia   Australia Other   245
4    Australia   New South Wales    85
..         ...               ...   ...
420    Uruguay           Juanico    12
421    Uruguay        Montevideo    11
422    Uruguay          Progreso    11
423    Uruguay          San Jose     3
424    Uruguay           Uruguay    24

[425 rows x 3 columns]

In [55]:
countries_reviewed.sort_values(by=['country', 'len'])

       country          province   len
1    Argentina             Other   536
0    Argentina  Mendoza Province  3264
2      Armenia           Armenia     2
6    Australia          Tasmania    42
4    Australia   New South Wales    85
..         ...               ...   ...
421    Uruguay        Montevideo    11
422    Uruguay          Progreso    11
420    Uruguay           Juanico    12
424    Uruguay           Uruguay    24
419    Uruguay         Canelones    43

[425 rows x 3 columns]

# Lecture 5. Data types and missing values

In [56]:
reviews.price.dtype

dtype('float64')

In [57]:
reviews.dtypes

country                   object
description               object
designation               object
points                     int64
price                    float64
province                  object
region_1                  object
region_2                  object
taster_name               object
taster_twitter_handle     object
title                     object
variety                   object
winery                    object
dtype: object

In [58]:
reviews.points.astype('float64')

0         87.0
1         87.0
2         87.0
3         87.0
4         87.0
          ...
129966    90.0
129967    90.0
129968    90.0
129969    90.0
129970    90.0
Name: points, Length: 129971, dtype: float64

In [59]:
reviews.index.dtype

dtype('int64')

In [60]:
reviews[pd.isnull(reviews.country)]

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
913,NaN,"Amber in color, this wine has aromas of peach ...",Asureti Valley,87,30.0,NaN,NaN,NaN,Mike DeSimone,@worldwineguys,Gotsa Family Wines 2014 Asureti Valley Chinuri,Chinuri,Gotsa Family Wines
3131,NaN,"Soft, fruity and juicy, this is a pleasant, si...",Partager,83,NaN,NaN,NaN,NaN,Roger Voss,@vossroger,Barton & Guestier NV Partager Red,Red Blend,Barton & Guestier
4243,NaN,"Violet-red in color, this semisweet wine has a...",Red Naturally Semi-Sweet,88,18.0,NaN,NaN,NaN,Mike DeSimone,@worldwineguys,Kakhetia Traditional Winemaking 2012 Red Natur...,Ojaleshi,Kakhetia Traditional Winemaking
9509,NaN,This mouthwatering blend starts with a nose of...,Theopetra Malagouzia-Assyrtiko,92,28.0,NaN,NaN,NaN,Susan Kostrzewa,@suskostrzewa,Tsililis 2015 Theopetra Malagouzia-Assyrtiko W...,White Blend,Tsililis
9750,NaN,This orange-style wine has a cloudy yellow-gol...,Orange Nikolaevo Vineyard,89,28.0,NaN,NaN,NaN,Jeff Jenssen,@worldwineguys,Ross-idi 2015 Orange Nikolaevo Vineyard Chardo...,Chardonnay,Ross-idi
...,...,...,...,...,...,...,...,...,...,...,...,...,...
124176,NaN,This Swiss red blend is composed of four varie...,Les Romaines,90,30.0,NaN,NaN,NaN,Jeff Jenssen,@worldwineguys,Les Frères Dutruy 2014 Les Romaines Red,Red Blend,Les Frères Dutruy
129407,NaN,Dry spicy aromas of dusty plum and tomato add ...,Reserve,89,22.0,NaN,NaN,NaN,Michael Schachner,@wineschach,El Capricho 2015 Reserve Cabernet Sauvignon,Cabernet Sauvignon,El Capricho
129408,NaN,El Capricho is one of Uruguay's more consisten...,Reserve,89,22.0,NaN,NaN,NaN,Michael Schachner,@wineschach,El Capricho 2015 Reserve Tempranillo,Tempranillo,El Capricho
129590,NaN,"A blend of 60% Syrah, 30% Cabernet Sauvignon a...",Shah,90,30.0,NaN,NaN,NaN,Mike DeSimone,@worldwineguys,Büyülübağ 2012 Shah Red,Red Blend,Büyülübağ
129900,NaN,This wine offers a delightful bouquet of black...,NaN,91,32.0,NaN,NaN,NaN,Mike DeSimone,@worldwineguys,Psagot 2014 Merlot,Merlot,Psagot

In [62]:
reviews.region_2.fillna('Unknown')

0                   Unknown
1                   Unknown
2         Willamette Valley
3                   Unknown
4         Willamette Valley
                ...
129966              Unknown
129967         Oregon Other
129968              Unknown
129969              Unknown
129970              Unknown
Name: region_2, Length: 129971, dtype: object

In [63]:
reviews.taster_twitter_handle.replace('@kerinokeefe', '@kerino')

0             @kerino
1          @vossroger
2         @paulgwine
3                 NaN
4         @paulgwine
             ...
129966            NaN
129967    @paulgwine
129968     @vossroger
129969     @vossroger
129970     @vossroger
Name: taster_twitter_handle, Length: 129971, dtype: object

# Lecture 6. Renaming and combining

In [64]:
reviews.rename(columns={'points': 'score'})

,country,description,designation,score,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks
...,...,...,...,...,...,...,...,...,...,...,...,...,...
129966,Germany,Notes of honeysuckle and cantaloupe sweeten th...,Brauneberger Juffer-Sonnenuhr Spätlese,90,28.0,Mosel,NaN,NaN,Anna Lee C. Iijima,NaN,Dr. H. Thanisch (Erben Müller-Burggraef) 2013 ...,Riesling,Dr. H. Thanisch (Erben Müller-Burggraef)
129967,US,Citation is given as much as a decade of bottl...,NaN,90,75.0,Oregon,Oregon,Oregon Other,Paul Gregutt,@paulgwine,Citation 2004 Pinot Noir (Oregon),Pinot Noir,Citation
129968,France,Well-drained gravel soil gives this wine its c...,Kritt,90,30.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Gresser 2013 Kritt Gewurztraminer (Als...,Gewürztraminer,Domaine Gresser
129969,France,"A dry style of Pinot Gris, this is crisp with ...",NaN,90,32.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Marcel Deiss 2012 Pinot Gris (Alsace),Pinot Gris,Domaine Marcel Deiss
129970,France,"Big, rich and off-dry, this is powered by inte...",Lieu-dit Harth Cuvée Caroline,90,21.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Schoffit 2012 Lieu-dit Harth Cuvée Car...,Gewürztraminer,Domaine Schoffit

In [65]:
reviews.rename(index={0: 'firstEntry', 1: 'secondEntry'})

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
firstEntry,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
secondEntry,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks
...,...,...,...,...,...,...,...,...,...,...,...,...,...
129966,Germany,Notes of honeysuckle and cantaloupe sweeten th...,Brauneberger Juffer-Sonnenuhr Spätlese,90,28.0,Mosel,NaN,NaN,Anna Lee C. Iijima,NaN,Dr. H. Thanisch (Erben Müller-Burggraef) 2013 ...,Riesling,Dr. H. Thanisch (Erben Müller-Burggraef)
129967,US,Citation is given as much as a decade of bottl...,NaN,90,75.0,Oregon,Oregon,Oregon Other,Paul Gregutt,@paulgwine,Citation 2004 Pinot Noir (Oregon),Pinot Noir,Citation
129968,France,Well-drained gravel soil gives this wine its c...,Kritt,90,30.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Gresser 2013 Kritt Gewurztraminer (Als...,Gewürztraminer,Domaine Gresser
129969,France,"A dry style of Pinot Gris, this is crisp with ...",NaN,90,32.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Marcel Deiss 2012 Pinot Gris (Alsace),Pinot Gris,Domaine Marcel Deiss
129970,France,"Big, rich and off-dry, this is powered by inte...",Lieu-dit Harth Cuvée Caroline,90,21.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Schoffit 2012 Lieu-dit Harth Cuvée Car...,Gewürztraminer,Domaine Schoffit

In [67]:
reviews.rename_axis('wines', axis="rows").rename_axis("fields", axis='columns')

fields,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
wines,,,,,,,,,,,,,
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks
...,...,...,...,...,...,...,...,...,...,...,...,...,...
129966,Germany,Notes of honeysuckle and cantaloupe sweeten th...,Brauneberger Juffer-Sonnenuhr Spätlese,90,28.0,Mosel,NaN,NaN,Anna Lee C. Iijima,NaN,Dr. H. Thanisch (Erben Müller-Burggraef) 2013 ...,Riesling,Dr. H. Thanisch (Erben Müller-Burggraef)
129967,US,Citation is given as much as a decade of bottl...,NaN,90,75.0,Oregon,Oregon,Oregon Other,Paul Gregutt,@paulgwine,Citation 2004 Pinot Noir (Oregon),Pinot Noir,Citation
129968,France,Well-drained gravel soil gives this wine its c...,Kritt,90,30.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Gresser 2013 Kritt Gewurztraminer (Als...,Gewürztraminer,Domaine Gresser
129969,France,"A dry style of Pinot Gris, this is crisp with ...",NaN,90,32.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Marcel Deiss 2012 Pinot Gris (Alsace),Pinot Gris,Domaine Marcel Deiss
129970,France,"Big, rich and off-dry, this is powered by inte...",Lieu-dit Harth Cuvée Caroline,90,21.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Schoffit 2012 Lieu-dit Harth Cuvée Car...,Gewürztraminer,Domaine Schoffit

In [68]:
canadian_youtube = pd.read_csv("CAvideos.csv")
british_youtube = pd.read_csv("GBvideos.csv")

pd.concat([canadian_youtube, british_youtube])

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description
0,n1WpP7iowLc,17.14.11,Eminem - Walk On Water (Audio) ft. Beyoncé,EminemVEVO,10,2017-11-10T17:00:03.000Z,"Eminem|""Walk""|""On""|""Water""|""Aftermath/Shady/In...",17158579,787425,43420,125882,https://i.ytimg.com/vi/n1WpP7iowLc/default.jpg,False,False,False,Eminem's new track Walk on Water ft. Beyoncé i...
1,0dBIkQ4Mz1M,17.14.11,PLUSH - Bad Unboxing Fan Mail,iDubbbzTV,23,2017-11-13T17:00:00.000Z,"plush|""bad unboxing""|""unboxing""|""fan mail""|""id...",1014651,127794,1688,13030,https://i.ytimg.com/vi/0dBIkQ4Mz1M/default.jpg,False,False,False,STill got a lot of packages. Probably will las...
2,5qpjK5DgCt4,17.14.11,"Racist Superman | Rudy Mancuso, King Bach & Le...",Rudy Mancuso,23,2017-11-12T19:05:24.000Z,"racist superman|""rudy""|""mancuso""|""king""|""bach""...",3191434,146035,5339,8181,https://i.ytimg.com/vi/5qpjK5DgCt4/default.jpg,False,False,False,WATCH MY PREVIOUS VIDEO ▶ \n\nSUBSCRIBE ► http...
3,d380meD0W0M,17.14.11,I Dare You: GOING BALD!?,nigahiga,24,2017-11-12T18:01:41.000Z,"ryan|""higa""|""higatv""|""nigahiga""|""i dare you""|""...",2095828,132239,1989,17518,https://i.ytimg.com/vi/d380meD0W0M/default.jpg,False,False,False,I know it's been a while since we did this sho...
4,2Vv-BfVoq4g,17.14.11,Ed Sheeran - Perfect (Official Music Video),Ed Sheeran,10,2017-11-09T11:04:14.000Z,"edsheeran|""ed sheeran""|""acoustic""|""live""|""cove...",33523622,1634130,21082,85067,https://i.ytimg.com/vi/2Vv-BfVoq4g/default.jpg,False,False,False,🎧: https://ad.gt/yt-perfect\n💰: https://atlant...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38911,l884wKofd54,18.14.06,Enrique Iglesias - MOVE TO MIAMI (Official Vid...,EnriqueIglesiasVEVO,10,2018-05-09T07:00:01.000Z,"Enrique Iglesias feat. Pitbull|""MOVE TO MIAMI""...",25066952,268088,12783,9933,https://i.ytimg.com/vi/l884wKofd54/default.jpg,False,False,False,NEW SONG - MOVE TO MIAMI feat. Pitbull (Click ...
38912,IP8k2xkhOdI,18.14.06,Jacob Sartorius - Up With It (Official Music V...,Jacob Sartorius,10,2018-05-11T17:09:16.000Z,"jacob sartorius|""jacob""|""up with it""|""jacob sa...",1492219,61998,13781,24330,https://i.ytimg.com/vi/IP8k2xkhOdI/default.jpg,False,False,False,THE OFFICIAL UP WITH IT MUSIC VIDEO!Get my new...
38913,Il-an3K9pjg,18.14.06,Anne-Marie - 2002 [Official Video],Anne-Marie,10,2018-05-08T11:05:08.000Z,"anne|""marie""|""anne-marie""|""2002""|""two thousand...",29641412,394830,8892,19988,https://i.ytimg.com/vi/Il-an3K9pjg/default.jpg,False,False,False,Get 2002 by Anne-Marie HERE ▶ http://ad.gt/200...
38914,-DRsfNObKIQ,18.14.06,Eleni Foureira - Fuego - Cyprus - LIVE - First...,Eurovision Song Contest,24,2018-05-08T20:32:32.000Z,"Eurovision Song Contest|""2018""|""Lisbon""|""Cypru...",14317515,151870,45875,26766,https://i.ytimg.com/vi/-DRsfNObKIQ/default.jpg,False,False,False,Eleni Foureira represented Cyprus at the first...
38915,4YFo4bdMO8Q,18.14.06,KYLE - Ikuyo feat. 2 Chainz & Sophia Black [A...,SuperDuperKyle,10,2018-05-11T04:06:35.000Z,"Kyle|""SuperDuperKyle""|""Ikuyo""|""2 Chainz""|""Soph...",607552,18271,274,1423,https://i.ytimg.com/vi/4YFo4bdMO8Q/default.jpg,False,False,False,Debut album 'Light of Mine' out now: http://ky...

In [69]:
left = canadian_youtube.set_index(['title', 'trending_date'])
right = british_youtube.set_index(['title', 'trending_date'])

left.join(right, lsuffix='_CAN', rsuffix='_UK')

                                                                 video_id_CAN  \
title                                              trending_date
!! THIS VIDEO IS NOTHING BUT PAIN !! | Getting ... 18.04.01       PNn8sECd7io
#1 Fortnite World Rank - 2,323 Solo Wins!          18.09.03       DvPW66IFhMI
#1 Fortnite World Rank - 2,330 Solo Wins!          18.10.03       EXEaMjFeiEk
#1 MOST ANTICIPATED VIDEO (Timber Frame House R... 17.20.12       bYvQmusLaxw
                                                   17.21.12       bYvQmusLaxw
...                                                                       ...
😲She Is So Nervous But BLOWS The ROOF After Tak... 18.02.05       WttN1Z0XF4k
                                                   18.29.04       WttN1Z0XF4k
                                                   18.30.04       WttN1Z0XF4k
🚨 BREAKING NEWS 🔴 Raja Live all Slot Channels W... 18.07.05       Wt9Gkpmbt44
🚨Active Shooter at YouTube Headquarters - LIVE ... 18.04.04       Az72jrKbANA

                                                                                channel_title_CAN  \
title                                              trending_date
!! THIS VIDEO IS NOTHING BUT PAIN !! | Getting ... 18.04.01                            Markiplier
#1 Fortnite World Rank - 2,323 Solo Wins!          18.09.03                        AlexRamiGaming
#1 Fortnite World Rank - 2,330 Solo Wins!          18.10.03                        AlexRamiGaming
#1 MOST ANTICIPATED VIDEO (Timber Frame House R... 17.20.12                  Pure Living for Life
                                                   17.21.12                  Pure Living for Life
...                                                                                           ...
😲She Is So Nervous But BLOWS The ROOF After Tak... 18.02.05                          How Talented
                                                   18.29.04                          How Talented
                                                   18.30.04                          How Talented
🚨 BREAKING NEWS 🔴 Raja Live all Slot Channels W... 18.07.05                         TheBigJackpot
🚨Active Shooter at YouTube Headquarters - LIVE ... 18.04.04       Right Side Broadcasting Network

                                                                  category_id_CAN  \
title                                              trending_date
!! THIS VIDEO IS NOTHING BUT PAIN !! | Getting ... 18.04.01                    20
#1 Fortnite World Rank - 2,323 Solo Wins!          18.09.03                    20
#1 Fortnite World Rank - 2,330 Solo Wins!          18.10.03                    20
#1 MOST ANTICIPATED VIDEO (Timber Frame House R... 17.20.12                    24
                                                   17.21.12                    24
...                                                                           ...
😲She Is So Nervous But BLOWS The ROOF After Tak... 18.02.05                    24
                                                   18.29.04                    24
                                                   18.30.04                    24
🚨 BREAKING NEWS 🔴 Raja Live all Slot Channels W... 18.07.05                    24
🚨Active Shooter at YouTube Headquarters - LIVE ... 18.04.04                    25

                                                                          publish_time_CAN  \
title                                              trending_date
!! THIS VIDEO IS NOTHING BUT PAIN !! | Getting ... 18.04.01       2018-01-03T19:33:53.000Z
#1 Fortnite World Rank - 2,323 Solo Wins!          18.09.03       2018-03-09T07:15:52.000Z
#1 Fortnite World Rank - 2,330 Solo Wins!          18.10.03       2018-03-10T06:26:17.000Z
#1 MOST ANTICIPATED VIDEO (Timber Frame House R... 17.20.12       2017-12-20T02:49:11.000Z
                                                   17.21.12       2017-12-20T02:49:11.000Z
...                                                                                    ...
😲She Is So Nervous But BLOWS The ROOF After Tak... 18.02.05       2018-04-28T19:40:58.000Z
                                                   18.29.04       2018-04-28T19:40:58.000Z
                                                   18.30.04       2018-04-28T19:40:58.000Z
🚨 BREAKING NEWS 🔴 Raja Live all Slot Channels W... 18.07.05       2018-05-07T06:58:59.000Z
🚨Active Shooter at YouTube Headquarters - LIVE ... 18.04.04       2018-04-03T23:12:37.000Z

                                                                                                           tags_CAN  \
title                                              trending_date
!! THIS VIDEO IS NOTHING BUT PAIN !! | Getting ... 18.04.01       getting over it|"markiplier"|"funny moments"|"...
#1 Fortnite World Rank - 2,323 Solo Wins!          18.09.03       PS4 Battle Royale|"PS4 Pro Battle Royale"|"Bat...
#1 Fortnite World Rank - 2,330 Solo Wins!          18.10.03       PS4 Battle Royale|"PS4 Pro Battle Royale"|"Bat...
#1 MOST ANTICIPATED VIDEO (Timber Frame House R... 17.20.12       timber frame|"timber framing"|"timber frame ra...
                                                   17.21.12       timber frame|"timber framing"|"timber frame ra...
...                                                                                                             ...
😲She Is So Nervous But BLOWS The ROOF After Tak... 18.02.05       bgt|"bgt 2018"|"britain got talent"|"britain´s...
                                                   18.29.04       bgt|"bgt 2018"|"britain got talent"|"britain´s...
                                                   18.30.04       bgt|"bgt 2018"|"britain got talent"|"britain´s...
🚨 BREAKING NEWS 🔴 Raja Live all Slot Channels W... 18.07.05       Slot Machine|"win"|"Gambling"|"Big Win"|"raja"...
🚨Active Shooter at YouTube Headquarters - LIVE ... 18.04.04       YouTube shooter|"YouTube active shooter"|"acti...

                                                                  views_CAN  \
title                                              trending_date
!! THIS VIDEO IS NOTHING BUT PAIN !! | Getting ... 18.04.01          835930
#1 Fortnite World Rank - 2,323 Solo Wins!          18.09.03          212838
#1 Fortnite World Rank - 2,330 Solo Wins!          18.10.03          200764
#1 MOST ANTICIPATED VIDEO (Timber Frame House R... 17.20.12           79152
                                                   17.21.12          232762
...                                                                     ...
😲She Is So Nervous But BLOWS The ROOF After Tak... 18.02.05          713400
                                                   18.29.04          231906
                                                   18.30.04          476253
🚨 BREAKING NEWS 🔴 Raja Live all Slot Channels W... 18.07.05           28973
🚨Active Shooter at YouTube Headquarters - LIVE ... 18.04.04          103513

                                                                  likes_CAN  \
title                                              trending_date
!! THIS VIDEO IS NOTHING BUT PAIN !! | Getting ... 18.04.01           47058
#1 Fortnite World Rank - 2,323 Solo Wins!          18.09.03            5199
#1 Fortnite World Rank - 2,330 Solo Wins!          18.10.03            5620
#1 MOST ANTICIPATED VIDEO (Timber Frame House R... 17.20.12            7761
                                                   17.21.12           15515
...                                                                     ...
😲She Is So Nervous But BLOWS The ROOF After Tak... 18.02.05            4684
                                                   18.29.04            1924
                                                   18.30.04            3417
🚨 BREAKING NEWS 🔴 Raja Live all Slot Channels W... 18.07.05            2167
🚨Active Shooter at YouTube Headquarters - LIVE ... 18.04.04            1722

                                                                  dislikes_CAN  \
title                                              trending_date
!! THIS VIDEO IS NOTHING BUT PAIN !! | Getting ... 18.04.01               1023
#1 Fortnite World Rank - 2,323 Solo Wins!          18.09.03                542
#1 Fortnite World Rank - 2,330 Solo Wins!          18.10.03                537
#1 MOST ANTICIPATED VIDEO (Timber Frame House R... 17.20.12                159
                                                   17.21.12                329
...                                                                        ...
😲She Is So Nervous But BLOWS The ROOF After Tak... 18.02.05                260
                                                   18.29.04                 78
                                                   18.30.04                176
🚨 BREAKING NEWS 🔴 Raja Live all Slot Channels W... 18.07.05                175
🚨Active Shooter at YouTube Headquarters - LIVE ... 18.04.04                181

                                                                  comment_count_CAN  \
title                                              trending_date
!! THIS VIDEO IS NOTHING BUT PAIN !! | Getting ... 18.04.01                    8250
#1 Fortnite World Rank - 2,323 Solo Wins!          18.09.03                      11
#1 Fortnite World Rank - 2,330 Solo Wins!          18.10.03                      45
#1 MOST ANTICIPATED VIDEO (Timber Frame House R... 17.20.12                    1965
                                                   17.21.12                    3601
...                                                                             ...
😲She Is So Nervous But BLOWS The ROOF After Tak... 18.02.05                     266
                                                   18.29.04                     146
                                                   18.30.04                     240
🚨 BREAKING NEWS 🔴 Raja Live all Slot Channels W... 18.07.05                      10
🚨Active Shooter at YouTube Headquarters - LIVE ... 18.04.04                      76

                                                                                              thumbnail_link_CAN  \
title                                              trending_date
!! THIS VIDEO IS NOTHING BUT PAIN !! | Getting ... 18.04.01       https://i.ytimg.com/vi/PNn8sECd7io/default.jpg
#1 Fortnite World Rank - 2,323 Solo Wins!          18.09.03       https://i.ytimg.com/vi/DvPW66IFhMI/default.jpg
#1 Fortnite World Rank - 2,330 Solo Wins!          18.10.03       https://i.ytimg.com/vi/EXEaMjFeiEk/default.jpg
#1 MOST ANTICIPATED VIDEO (Timber Frame House R... 17.20.12       https://i.ytimg.com/vi/bYvQmusLaxw/default.jpg
                                                   17.21.12       https://i.ytimg.com/vi/bYvQmusLaxw/default.jpg
...                                                                                                          ...
😲She Is So Nervous But BLOWS The ROOF After Tak... 18.02.05       https://i.ytimg.com/vi/WttN1Z0XF4k/default.jpg
                                                   18.29.04       https://i.ytimg.com/vi/WttN1Z0XF4k/default.jpg
                                                   18.30.04       https://i.ytimg.com/vi/WttN1Z0XF4k/default.jpg
🚨 BREAKING NEWS 🔴 Raja Live all Slot Channels W... 18.07.05       https://i.ytimg.com/vi/Wt9Gkpmbt44/default.jpg
🚨Active Shooter at YouTube Headquarters - LIVE ... 18.04.04       https://i.ytimg.com/vi/Az72jrKbANA/default.jpg

                                                                  ...  \
title                                              trending_date  ...
!! THIS VIDEO IS NOTHING BUT PAIN !! | Getting ... 18.04.01       ...
#1 Fortnite World Rank - 2,323 Solo Wins!          18.09.03       ...
#1 Fortnite World Rank - 2,330 Solo Wins!          18.10.03       ...
#1 MOST ANTICIPATED VIDEO (Timber Frame House R... 17.20.12       ...
                                                   17.21.12       ...
...                                                               ...
😲She Is So Nervous But BLOWS The ROOF After Tak... 18.02.05       ...
                                                   18.29.04       ...
                                                   18.30.04       ...
🚨 BREAKING NEWS 🔴 Raja Live all Slot Channels W... 18.07.05       ...
🚨Active Shooter at YouTube Headquarters - LIVE ... 18.04.04       ...

                                                                  tags_UK  \
title                                              trending_date
!! THIS VIDEO IS NOTHING BUT PAIN !! | Getting ... 18.04.01           NaN
#1 Fortnite World Rank - 2,323 Solo Wins!          18.09.03           NaN
#1 Fortnite World Rank - 2,330 Solo Wins!          18.10.03           NaN
#1 MOST ANTICIPATED VIDEO (Timber Frame House R... 17.20.12           NaN
                                                   17.21.12           NaN
...                                                                   ...
😲She Is So Nervous But BLOWS The ROOF After Tak... 18.02.05           NaN
                                                   18.29.04           NaN
                                                   18.30.04           NaN
🚨 BREAKING NEWS 🔴 Raja Live all Slot Channels W... 18.07.05           NaN
🚨Active Shooter at YouTube Headquarters - LIVE ... 18.04.04           NaN

                                                                  views_UK  \
title                                              trending_date
!! THIS VIDEO IS NOTHING BUT PAIN !! | Getting ... 18.04.01            NaN
#1 Fortnite World Rank - 2,323 Solo Wins!          18.09.03            NaN
#1 Fortnite World Rank - 2,330 Solo Wins!          18.10.03            NaN
#1 MOST ANTICIPATED VIDEO (Timber Frame House R... 17.20.12            NaN
                                                   17.21.12            NaN
...                                                                    ...
😲She Is So Nervous But BLOWS The ROOF After Tak... 18.02.05            NaN
                                                   18.29.04            NaN
                                                   18.30.04            NaN
🚨 BREAKING NEWS 🔴 Raja Live all Slot Channels W... 18.07.05            NaN
🚨Active Shooter at YouTube Headquarters - LIVE ... 18.04.04            NaN

                                                                  likes_UK  \
title                                              trending_date
!! THIS VIDEO IS NOTHING BUT PAIN !! | Getting ... 18.04.01            NaN
#1 Fortnite World Rank - 2,323 Solo Wins!          18.09.03            NaN
#1 Fortnite World Rank - 2,330 Solo Wins!          18.10.03            NaN
#1 MOST ANTICIPATED VIDEO (Timber Frame House R... 17.20.12            NaN
                                                   17.21.12            NaN
...                                                                    ...
😲She Is So Nervous But BLOWS The ROOF After Tak... 18.02.05            NaN
                                                   18.29.04            NaN
                                                   18.30.04            NaN
🚨 BREAKING NEWS 🔴 Raja Live all Slot Channels W... 18.07.05            NaN
🚨Active Shooter at YouTube Headquarters - LIVE ... 18.04.04            NaN

                                                                 dislikes_UK  \
title                                              trending_date
!! THIS VIDEO IS NOTHING BUT PAIN !! | Getting ... 18.04.01              NaN
#1 Fortnite World Rank - 2,323 Solo Wins!          18.09.03              NaN
#1 Fortnite World Rank - 2,330 Solo Wins!          18.10.03              NaN
#1 MOST ANTICIPATED VIDEO (Timber Frame House R... 17.20.12              NaN
                                                   17.21.12              NaN
...                                                                      ...
😲She Is So Nervous But BLOWS The ROOF After Tak... 18.02.05              NaN
                                                   18.29.04              NaN
                                                   18.30.04              NaN
🚨 BREAKING NEWS 🔴 Raja Live all Slot Channels W... 18.07.05              NaN
🚨Active Shooter at YouTube Headquarters - LIVE ... 18.04.04              NaN

                                                                 comment_count_UK  \
title                                              trending_date
!! THIS VIDEO IS NOTHING BUT PAIN !! | Getting ... 18.04.01                   NaN
#1 Fortnite World Rank - 2,323 Solo Wins!          18.09.03                   NaN
#1 Fortnite World Rank - 2,330 Solo Wins!          18.10.03                   NaN
#1 MOST ANTICIPATED VIDEO (Timber Frame House R... 17.20.12                   NaN
                                                   17.21.12                   NaN
...                                                                           ...
😲She Is So Nervous But BLOWS The ROOF After Tak... 18.02.05                   NaN
                                                   18.29.04                   NaN
                                                   18.30.04                   NaN
🚨 BREAKING NEWS 🔴 Raja Live all Slot Channels W... 18.07.05                   NaN
🚨Active Shooter at YouTube Headquarters - LIVE ... 18.04.04                   NaN

                                                                 thumbnail_link_UK  \
title                                              trending_date
!! THIS VIDEO IS NOTHING BUT PAIN !! | Getting ... 18.04.01                    NaN
#1 Fortnite World Rank - 2,323 Solo Wins!          18.09.03                    NaN
#1 Fortnite World Rank - 2,330 Solo Wins!          18.10.03                    NaN
#1 MOST ANTICIPATED VIDEO (Timber Frame House R... 17.20.12                    NaN
                                                   17.21.12                    NaN
...                                                                            ...
😲She Is So Nervous But BLOWS The ROOF After Tak... 18.02.05                    NaN
                                                   18.29.04                    NaN
                                                   18.30.04                    NaN
🚨 BREAKING NEWS 🔴 Raja Live all Slot Channels W... 18.07.05                    NaN
🚨Active Shooter at YouTube Headquarters - LIVE ... 18.04.04                    NaN

                                                                  comments_disabled_UK  \
title                                              trending_date
!! THIS VIDEO IS NOTHING BUT PAIN !! | Getting ... 18.04.01                        NaN
#1 Fortnite World Rank - 2,323 Solo Wins!          18.09.03                        NaN
#1 Fortnite World Rank - 2,330 Solo Wins!          18.10.03                        NaN
#1 MOST ANTICIPATED VIDEO (Timber Frame House R... 17.20.12                        NaN
                                                   17.21.12                        NaN
...                                                                                ...
😲She Is So Nervous But BLOWS The ROOF After Tak... 18.02.05                        NaN
                                                   18.29.04                        NaN
                                                   18.30.04                        NaN
🚨 BREAKING NEWS 🔴 Raja Live all Slot Channels W... 18.07.05                        NaN
🚨Active Shooter at YouTube Headquarters - LIVE ... 18.04.04                        NaN

                                                                 ratings_disabled_UK  \
title                                              trending_date
!! THIS VIDEO IS NOTHING BUT PAIN !! | Getting ... 18.04.01                      NaN
#1 Fortnite World Rank - 2,323 Solo Wins!          18.09.03                      NaN
#1 Fortnite World Rank - 2,330 Solo Wins!          18.10.03                      NaN
#1 MOST ANTICIPATED VIDEO (Timber Frame House R... 17.20.12                      NaN